Added support for Webdriver Standalone
webdriverio-community/wdio-intercept-service pull request #139
Opened 2021-06-27 14:57 UTC by juenobueno

The before function is currently already being called with the arguments of config, capabilities, browser.
Since the browser object will be the same, this change allows the service to be compatible with the CLI Testrunner
and WebDriver standalone. Documentation in the README and a new test has been added also.

2021-06-27 15:01 UTC, juenobueno commented
See linked issue for more description

2021-07-29 23:46 UTC, juenobueno commented
@chmanie Could you please take a look at this PR? :)

2021-07-30 07:13 UTC, christian-bromann requested changes
Some comments

2021-07-30 07:13 UTC, christian-bromann commented on index.js
> +  before(config, capabilities, browser) {
How about using underscore so we signal that we only use `browser` here.
```suggestion
  before(_, __, browser) {
```

2021-07-30 07:13 UTC, christian-bromann commented on index.js
> +exports.WebdriverAjax = WebdriverAjax;
no need for an extra named export
```suggestion
```

2021-07-30 07:13 UTC, christian-bromann commented on README.md
> +import { WebdriverAjax } from 'wdio-intercept-service-main'
```suggestion
import WebdriverAjax from 'wdio-intercept-service'
```

2021-07-30 07:13 UTC, christian-bromann commented on test/spec/plugin_test.js
> +const { WebdriverAjax } = require('../../index');
```suggestion
const WebdriverAjax = require('../../index').default;
```

2021-08-02 00:58 UTC, juenobueno commented
👍 Requested changes have been made, thanks for the feedback

2021-08-02 07:25 UTC, christian-bromann approved these changes
👍

2021-08-02 07:30 UTC, juenobueno commented
👀  Looking into failed tests

2021-08-02 08:35 UTC, juenobueno commented
In order to get the tests to run locally, I had to update `chromedriver` to `v92`. Not sure if this will fix the tests in the CI.

2021-08-02 09:06 UTC, christian-bromann commented
Awesome, thanks!

2021-08-02 09:06 UTC, merged

2021-08-02 09:15 UTC, juenobueno commented
@christian-bromann Will a new version of this package be published to npm automatically? Apologies if this is a silly question 😅

2021-08-02 10:53 UTC, christian-bromann commented
No but just triggered the release pipeline.